#!/bin/bash
createtestfile() {
  local year=$1
  local day=$2
  local paddedDay=$(printf "%02d" $day)
  local type1=${3:-Any}
  local type2=${4:-Any}

  if [[ -z $year || -z $day ]]; then
    echo "Missing params."
    exit 1
  fi

  local puzzledir="src/test/kotlin/dev/garlicbread/aoc/y$year/"
  if [[ ! -e "$puzzledir" ]]; then
    mkdir "$puzzledir"
  fi

  local file="${puzzledir}Problem${paddedDay}Test.kt"
  if [[ -e $file ]]; then
    read -p "File exists: ${file}. Overwrite? (y/N) " -r overwrite
    [[ "$overwrite" =~ ^[yY]$ ]] || return 1
  fi

  echo "Creating test class: $file"
  echo "package dev.garlicbread.aoc.y${year}

import com.google.common.truth.Truth.assertThat
import dev.garlicbread.aoc.Solver
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test

@DisplayName(\"$year Day $day\")
internal class Problem${paddedDay}Test {

    @BeforeEach
    fun setUp() {
        Solver.suffix = \"\"
        Solver.inputProvider = Solver.defaultInputProvider
    }

    @Nested
    @DisplayName(\"Part 1\")
    inner class Part1 {
        @Test
        @DisplayName(\"Example Input 1\")
        fun \`Matches example 1\`() {
            Solver.suffix = \"_1\"
            val answer = Problem${paddedDay}().solvePartOne()
            assertThat(answer).isEqualTo(TODO())
        }

        @Test
        @DisplayName(\"Actual Input\")
        fun \`Matches actual\`() {
            val answer = Problem${paddedDay}().solvePartOne()
            assertThat(answer).isEqualTo(TODO())
        }
    }

    @Nested
    @DisplayName(\"Part 2\")
    inner class Part2 {
        @Test
        @DisplayName(\"Example Input 1\")
        fun \`Matches example 1\`() {
            Solver.suffix = \"_1\"
            val answer = Problem${paddedDay}().solvePartTwo()
            assertThat(answer).isEqualTo(TODO())
        }

        @Test
        @DisplayName(\"Actual Input\")
        fun \`Matches actual\`() {
            val answer = Problem${paddedDay}().solvePartTwo()
            assertThat(answer).isEqualTo(TODO())
        }
    }
}" >"${file}"

  local inputfolder=src/test/resources/$year/
  local inputfile="${inputfolder}input${day}_1.in"
  if [[ -e $inputfile ]]; then
    read -p "File exists: ${inputfile}. Overwrite? (y/N) " -r overwrite
    [[ "$overwrite" =~ ^[yY]$ ]] || return 1
  fi

  echo "Creating test input file: $inputfile"
  if [[ ! -d $inputfolder ]]; then
    mkdir "$inputfolder"
  fi
  touch "$inputfile"

  return $?
}